
name: Schedule telegram bot MorningLabor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '18 1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: node index.js
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
